services:
  web:
    profiles:
      - prod
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:5000"

    environment:
      APP_ENV: production
      SECRET_KEY: ${SECRET_KEY:-change-me}

    command: gunicorn -w 2 -b 0.0.0.0:5000 'app:create_app()'

  localweb:
    profiles:
      - dev
    build:
      context: .
      dockerfile: dockerfile
    command: flask --app app run --debug
    ports:
      - "80:5000"

    environment:
      APP_ENV: development
      SECRET_KEY: ${SECRET_KEY:-dev-only-change-me}
