//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub mod prelude;

pub mod job;
pub mod membership;
pub mod permission;
pub mod role;
pub mod role_permissions;
pub mod user;
pub mod user_roles;
