[package]
name = "web-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
# The frontend framework
yew = {version = "0.21", features = ["csr"]}
yew-router = "0.18"
yew_icons = {version = "0.8", features = ["LucideMenu", "BootstrapBriefcase"]}
gloo = {version = "0.10.0", features = ["storage"]}
# A rust serialization library for interacting data between the backend and frontend
serde = { version = "1.0.188", features = ["derive"] }
