name: vagasemaraxa.com.br CD
on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      
      - name: Restauração do Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Instalação do Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"
      
      - name: Adicionar WASM como alvo de compilação
        run: |
          rustup target add wasm32-unknown-unknown
        
      - name: Compilação do WASM do subdomínio WWW
        run: trunk build --dist ./project/dist --release ${{github.workspace}}/project/frontend/www/index.html
      
      - name: Compilação do WASM do subdomínio ADMIN
        run: trunk build --public-url /admin/ --dist ./project/dist/admin --release ${{github.workspace}}/project/frontend/admin/index.html

      - name: Exposição da chave secreta
        run: echo ${{ secrets.SERVER_SECRET_KEY }} >> ./keyring_server.txt & ls .
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy do servidor
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "project/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}

      # - name: Configuração do SSH
      #   run: |
      #     env
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     ssh-keyscan -p 22 -t ed25519 ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
  
      # - name: Deploy da distribuição do Frontend
      #   run: |
      #     rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" ./dist ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}/dist
  

      